### ISSUE TITLE
loads site completely 

### ISSUE THREAD

**Issue by maartenkling** [collective/collective.polls#81]
https://github.com/collective/collective.polls/blob/master/src/collective/polls/portlet/voteportlet.pt#L26
This call makes the site load 2times, when setting a ipdb at a random viewlet in the site, its called twice. when removing the condition everything is back to normal again.

Should it be         tal:condition="nocall:has_poll">  ?

**Comment by hvelarde** [comment]
@maartenkling is this still happening?

**Comment by maartenkling** [comment]
If the line is there, then yes :)

For my own project i overruled the complete file to alter it.

**Comment by hvelarde** [comment]
seems it was fixed at some point
