### ISSUE TITLE
Create a mixin to share methods from view and tile

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.polls#88]
This [pull request](https://github.com/collective/collective.polls/pull/87/files) duplicated the methods of the view into the tile.

It is better to have a mixin to hold these methods, this way we have just one place to change, like we did in [sc.photogallery](https://github.com/simplesconsultoria/sc.photogallery/blob/master/src/sc/photogallery/utils.py#L6-L20)

**Comment by hvelarde** [comment]
@rodfersou can we close this one?

**Comment by rodfersou** [comment]
yes
